In [76]:
import numpy as np
A = np.array([
    [4.00, 3.50, 80.00],
    [5.00, 2.50, 35.00],
    [4.50, 2.50, 48.00]
])

In [77]:
A

array([[ 4. ,  3.5, 80. ],
       [ 5. ,  2.5, 35. ],
       [ 4.5,  2.5, 48. ]])

In [78]:
Target=A[:,2]
Target

array([80., 35., 48.])

In [79]:
D=A[:, 0:2]
D

array([[4. , 3.5],
       [5. , 2.5],
       [4.5, 2.5]])

In [80]:
array2 = np.append(np.ones((D.shape[0], 1)), D, axis=1)
array2

array([[1. , 4. , 3.5],
       [1. , 5. , 2.5],
       [1. , 4.5, 2.5]])

In [81]:
B=np.transpose(array2)
B

array([[1. , 1. , 1. ],
       [4. , 5. , 4.5],
       [3.5, 2.5, 2.5]])

In [82]:
C=np. dot(B,array2)

In [83]:
E=np.linalg.inv(C)
E

array([[363.5, -53. , -44. ],
       [-53. ,   8. ,   6. ],
       [-44. ,   6. ,   6. ]])

In [84]:
F=np.dot(E,B)

In [85]:
G=np.dot(F,Target)
G

array([117.5, -26. ,  19. ])