In [6]:
import numpy as np
A=np.array([[3,7,4,17,12,24,50],
[2,12,2,17,16,19,51],
[1,9,9,16,19,8,76],
[6,2,2,12,21,25,57],
[6,12,9,17,17,7,61],
[1,4,4,3,17,8,52],
[2,10,7,23,3,19,94],
[6,6,6,16,11,13,50],
[2,8,6,20,20,10,77],
[6,3,6,15,13,17,52],
[1,4,4,6,24,23,66],
[4,7,4,25,21,5,98],
[8,10,5,17,6,13,86],
[3,2,3,12,19,16,61],
[6,5,9,6,6,10,59],
[8,10,9,23,23,5,98],
[4,6,8,20,6,24,71],
[7,4,7,16,20,8,61],
[2,8,3,13,5,7,73]])


In [7]:
A

array([[ 3,  7,  4, 17, 12, 24, 50],
       [ 2, 12,  2, 17, 16, 19, 51],
       [ 1,  9,  9, 16, 19,  8, 76],
       [ 6,  2,  2, 12, 21, 25, 57],
       [ 6, 12,  9, 17, 17,  7, 61],
       [ 1,  4,  4,  3, 17,  8, 52],
       [ 2, 10,  7, 23,  3, 19, 94],
       [ 6,  6,  6, 16, 11, 13, 50],
       [ 2,  8,  6, 20, 20, 10, 77],
       [ 6,  3,  6, 15, 13, 17, 52],
       [ 1,  4,  4,  6, 24, 23, 66],
       [ 4,  7,  4, 25, 21,  5, 98],
       [ 8, 10,  5, 17,  6, 13, 86],
       [ 3,  2,  3, 12, 19, 16, 61],
       [ 6,  5,  9,  6,  6, 10, 59],
       [ 8, 10,  9, 23, 23,  5, 98],
       [ 4,  6,  8, 20,  6, 24, 71],
       [ 7,  4,  7, 16, 20,  8, 61],
       [ 2,  8,  3, 13,  5,  7, 73]])

In [8]:
Target=A[:,6]
Target

array([50, 51, 76, 57, 61, 52, 94, 50, 77, 52, 66, 98, 86, 61, 59, 98, 71,
       61, 73])

In [9]:
D=A[:, 0:6]
D

array([[ 3,  7,  4, 17, 12, 24],
       [ 2, 12,  2, 17, 16, 19],
       [ 1,  9,  9, 16, 19,  8],
       [ 6,  2,  2, 12, 21, 25],
       [ 6, 12,  9, 17, 17,  7],
       [ 1,  4,  4,  3, 17,  8],
       [ 2, 10,  7, 23,  3, 19],
       [ 6,  6,  6, 16, 11, 13],
       [ 2,  8,  6, 20, 20, 10],
       [ 6,  3,  6, 15, 13, 17],
       [ 1,  4,  4,  6, 24, 23],
       [ 4,  7,  4, 25, 21,  5],
       [ 8, 10,  5, 17,  6, 13],
       [ 3,  2,  3, 12, 19, 16],
       [ 6,  5,  9,  6,  6, 10],
       [ 8, 10,  9, 23, 23,  5],
       [ 4,  6,  8, 20,  6, 24],
       [ 7,  4,  7, 16, 20,  8],
       [ 2,  8,  3, 13,  5,  7]])

In [10]:
array2 = np.append([[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1]],D, axis = 1)
array2

array([[ 1,  3,  7,  4, 17, 12, 24],
       [ 1,  2, 12,  2, 17, 16, 19],
       [ 1,  1,  9,  9, 16, 19,  8],
       [ 1,  6,  2,  2, 12, 21, 25],
       [ 1,  6, 12,  9, 17, 17,  7],
       [ 1,  1,  4,  4,  3, 17,  8],
       [ 1,  2, 10,  7, 23,  3, 19],
       [ 1,  6,  6,  6, 16, 11, 13],
       [ 1,  2,  8,  6, 20, 20, 10],
       [ 1,  6,  3,  6, 15, 13, 17],
       [ 1,  1,  4,  4,  6, 24, 23],
       [ 1,  4,  7,  4, 25, 21,  5],
       [ 1,  8, 10,  5, 17,  6, 13],
       [ 1,  3,  2,  3, 12, 19, 16],
       [ 1,  6,  5,  9,  6,  6, 10],
       [ 1,  8, 10,  9, 23, 23,  5],
       [ 1,  4,  6,  8, 20,  6, 24],
       [ 1,  7,  4,  7, 16, 20,  8],
       [ 1,  2,  8,  3, 13,  5,  7]])

In [11]:
B=np.transpose(array2)

In [12]:
B

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1],
       [ 3,  2,  1,  6,  6,  1,  2,  6,  2,  6,  1,  4,  8,  3,  6,  8,
         4,  7,  2],
       [ 7, 12,  9,  2, 12,  4, 10,  6,  8,  3,  4,  7, 10,  2,  5, 10,
         6,  4,  8],
       [ 4,  2,  9,  2,  9,  4,  7,  6,  6,  6,  4,  4,  5,  3,  9,  9,
         8,  7,  3],
       [17, 17, 16, 12, 17,  3, 23, 16, 20, 15,  6, 25, 17, 12,  6, 23,
        20, 16, 13],
       [12, 16, 19, 21, 17, 17,  3, 11, 20, 13, 24, 21,  6, 19,  6, 23,
         6, 20,  5],
       [24, 19,  8, 25,  7,  8, 19, 13, 10, 17, 23,  5, 13, 16, 10,  5,
        24,  8,  7]])

In [13]:
C=np. dot(B,array2)

In [14]:
E=np.linalg.inv(C)
E

array([[ 2.20983877e+00, -4.00839273e-02, -6.08469605e-02,
        -7.40329509e-02, -3.64447026e-03, -3.55138880e-02,
        -4.25661210e-02],
       [-4.00839273e-02,  1.19117932e-02,  3.05481344e-03,
        -3.43528047e-03, -1.57510337e-03,  3.96943156e-04,
         6.06559668e-04],
       [-6.08469605e-02,  3.05481344e-03,  1.00697054e-02,
        -1.46952078e-03, -2.87225907e-03,  1.05990864e-03,
         1.24441834e-03],
       [-7.40329509e-02, -3.43528047e-03, -1.46952078e-03,
         1.31527644e-02, -3.43885121e-04,  6.64227055e-04,
         1.42752190e-03],
       [-3.64447026e-03, -1.57510337e-03, -2.87225907e-03,
        -3.43885121e-04,  2.58156794e-03, -2.71534008e-04,
        -3.21083760e-04],
       [-3.55138880e-02,  3.96943156e-04,  1.05990864e-03,
         6.64227055e-04, -2.71534008e-04,  1.42464901e-03,
         4.53470200e-04],
       [-4.25661210e-02,  6.06559668e-04,  1.24441834e-03,
         1.42752190e-03, -3.21083760e-04,  4.53470200e-04,
         1.5940623

In [15]:
F=np.dot(E,B)

In [16]:
G=np.dot(F,Target)

In [17]:
G

array([55.21198635, -0.96167903, -0.19654132,  0.45088493,  1.73316932,
       -0.08821606, -0.72355224])

***DatasetBased***

In [20]:
import pandas as pd
AA = pd.read_csv('Example2.csv', header=0)
AA.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Example2.csv'

In [ ]:
T1 = AA.to_numpy()

In [ ]:
Tar=T1[:,6]
Tar

array([50, 51, 76, 57, 61, 52, 94, 50, 77, 52, 66, 98, 86, 61, 59, 98, 71,
       61, 73], dtype=int64)

In [ ]:
D1=T1[:, 0:6]
D1

array([[ 3,  7,  4, 17, 12, 24],
       [ 2, 12,  2, 17, 16, 19],
       [ 1,  9,  9, 16, 19,  8],
       [ 6,  2,  2, 12, 21, 25],
       [ 6, 12,  9, 17, 17,  7],
       [ 1,  4,  4,  3, 17,  8],
       [ 2, 10,  7, 23,  3, 19],
       [ 6,  6,  6, 16, 11, 13],
       [ 2,  8,  6, 20, 20, 10],
       [ 6,  3,  6, 15, 13, 17],
       [ 1,  4,  4,  6, 24, 23],
       [ 4,  7,  4, 25, 21,  5],
       [ 8, 10,  5, 17,  6, 13],
       [ 3,  2,  3, 12, 19, 16],
       [ 6,  5,  9,  6,  6, 10],
       [ 8, 10,  9, 23, 23,  5],
       [ 4,  6,  8, 20,  6, 24],
       [ 7,  4,  7, 16, 20,  8],
       [ 2,  8,  3, 13,  5,  7]], dtype=int64)

In [ ]:
array3 = np.append([[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1],[1]],D1, axis = 1)
array3

array([[ 1,  3,  7,  4, 17, 12, 24],
       [ 1,  2, 12,  2, 17, 16, 19],
       [ 1,  1,  9,  9, 16, 19,  8],
       [ 1,  6,  2,  2, 12, 21, 25],
       [ 1,  6, 12,  9, 17, 17,  7],
       [ 1,  1,  4,  4,  3, 17,  8],
       [ 1,  2, 10,  7, 23,  3, 19],
       [ 1,  6,  6,  6, 16, 11, 13],
       [ 1,  2,  8,  6, 20, 20, 10],
       [ 1,  6,  3,  6, 15, 13, 17],
       [ 1,  1,  4,  4,  6, 24, 23],
       [ 1,  4,  7,  4, 25, 21,  5],
       [ 1,  8, 10,  5, 17,  6, 13],
       [ 1,  3,  2,  3, 12, 19, 16],
       [ 1,  6,  5,  9,  6,  6, 10],
       [ 1,  8, 10,  9, 23, 23,  5],
       [ 1,  4,  6,  8, 20,  6, 24],
       [ 1,  7,  4,  7, 16, 20,  8],
       [ 1,  2,  8,  3, 13,  5,  7]], dtype=int64)

In [ ]:
B1=np.transpose(array3)

In [ ]:
B1

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1],
       [ 3,  2,  1,  6,  6,  1,  2,  6,  2,  6,  1,  4,  8,  3,  6,  8,
         4,  7,  2],
       [ 7, 12,  9,  2, 12,  4, 10,  6,  8,  3,  4,  7, 10,  2,  5, 10,
         6,  4,  8],
       [ 4,  2,  9,  2,  9,  4,  7,  6,  6,  6,  4,  4,  5,  3,  9,  9,
         8,  7,  3],
       [17, 17, 16, 12, 17,  3, 23, 16, 20, 15,  6, 25, 17, 12,  6, 23,
        20, 16, 13],
       [12, 16, 19, 21, 17, 17,  3, 11, 20, 13, 24, 21,  6, 19,  6, 23,
         6, 20,  5],
       [24, 19,  8, 25,  7,  8, 19, 13, 10, 17, 23,  5, 13, 16, 10,  5,
        24,  8,  7]], dtype=int64)

In [ ]:
C1=np. dot(B1,array3)

In [ ]:
C1

array([[  19,   78,  129,  107,  294,  279,  261],
       [  78,  426,  528,  475, 1266, 1129, 1017],
       [ 129,  528, 1057,  768, 2179, 1813, 1654],
       [ 107,  475,  768,  709, 1719, 1530, 1353],
       [ 294, 1266, 2179, 1719, 5170, 4281, 3952],
       [ 279, 1129, 1813, 1530, 4281, 4919, 3698],
       [ 261, 1017, 1654, 1353, 3952, 3698, 4451]], dtype=int64)

In [ ]:
E1=np.linalg.inv(C1)
E1

array([[ 2.20983877e+00, -4.00839273e-02, -6.08469605e-02,
        -7.40329509e-02, -3.64447026e-03, -3.55138880e-02,
        -4.25661210e-02],
       [-4.00839273e-02,  1.19117932e-02,  3.05481344e-03,
        -3.43528047e-03, -1.57510337e-03,  3.96943156e-04,
         6.06559668e-04],
       [-6.08469605e-02,  3.05481344e-03,  1.00697054e-02,
        -1.46952078e-03, -2.87225907e-03,  1.05990864e-03,
         1.24441834e-03],
       [-7.40329509e-02, -3.43528047e-03, -1.46952078e-03,
         1.31527644e-02, -3.43885121e-04,  6.64227055e-04,
         1.42752190e-03],
       [-3.64447026e-03, -1.57510337e-03, -2.87225907e-03,
        -3.43885121e-04,  2.58156794e-03, -2.71534008e-04,
        -3.21083760e-04],
       [-3.55138880e-02,  3.96943156e-04,  1.05990864e-03,
         6.64227055e-04, -2.71534008e-04,  1.42464901e-03,
         4.53470200e-04],
       [-4.25661210e-02,  6.06559668e-04,  1.24441834e-03,
         1.42752190e-03, -3.21083760e-04,  4.53470200e-04,
         1.5940623

In [ ]:
F1=np.dot(E1,B1)

In [ ]:
G1=np.dot(F1,Tar)

In [ ]:
G1

array([55.21198635, -0.96167903, -0.19654132,  0.45088493,  1.73316932,
       -0.08821606, -0.72355224])

***Model***

In [5]:
import pandas as pd
AA1 = pd.read_csv('Example2.csv', header=0)
AA1.head()

F1  F2  F3  F4  F5  F6   T
0   3   7   4  17  12  24  50
1   2  12   2  17  16  19  51
2   1   9   9  16  19   8  76
3   6   2   2  12  21  25  57
4   6  12   9  17  17   7  61

In [6]:
TrainX = AA1.drop(['T'], axis='columns')
TrainX.head()

F1  F2  F3  F4  F5  F6
0   3   7   4  17  12  24
1   2  12   2  17  16  19
2   1   9   9  16  19   8
3   6   2   2  12  21  25
4   6  12   9  17  17   7

In [7]:
TrainY=AA1['T']
TrainY

0     50
1     51
2     76
3     57
4     61
5     52
6     94
7     50
8     77
9     52
10    66
11    98
12    86
13    61
14    59
15    98
16    71
17    61
18    73
Name: T, dtype: int64

In [8]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(TrainX, TrainY)

LinearRegression()

In [10]:
# Get the slope (coefficient) and intercept
slope = model.coef_
intercept = model.intercept_

print(f"Slope: {slope}")
print(f"Intercept: {intercept}")

Slope: [-0.96167903 -0.19654132  0.45088493  1.73316932 -0.08821606 -0.72355224]
Intercept: 55.211986350794504


In [ ]:
model.predict([[3,7,4,17,12,24]])

C:\Users\Md. Atiqur Rahman\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([63.79473182])